### ISSUE TITLE
Graag Feedback Op Opdracht 1

### ISSUE THREAD

**Issue by FaunaOS** [techgrounds/techgrounds-Jordan-Portfolio#1]
Hoi Jeroen & Marcel,

Kunnen jullie kijken of opdracht 1 goed is gelukt
- Werken de links naar de pngs?
- Is de uitleg duidelijk van de stappen die ik heb genomen?
- Hoe is de opmaak, zal ik deze nog aanpassen in de stijl van de template file die door Techgrounds is gegeven?

https://github.com/techgrounds/techgrounds-Jordan-Portfolio/blob/67868d11b438545c7facb48b7df5f709b7d031d4/00_templates/%5BGIT-01%5D%20Opdracht%201.md

**Comment by koekienator** [comment]
Hey Jordan,

De plaatjes werken allemaal goed. 
Behalve plaatje 2.iii. (deze is niet gelinkt vanuit 00_Include)

Git en Github Desktop staan door elkaar heen.
Zou deze apart houden voor overzicht of benoemen waar in je op dat moment werkt.

Stap gewijs feedback, volgens jouw eigen nummering:
3. Eerst een commit dan kan je pas een push doen.
4. Hoe ben je bij het toevoegen van een collaborateur gekomen, is dit in Git, Github of Github desktop?

Heb zelf geen Git gedaan, kan ik niet veel feedback over geven. 
Iets meer omschrijving dan één zin kan geen kwaad. 

De opmaak is best prima met lijsten in lijsten structuur.
Zou zelf misschien 2. -> 2.1 -> 2.1.1 doen i.pv. verschillende stijlen van nummering.

**Comment by FaunaOS** [comment]
@koekienator Dankjewel voor je uitgebreide feedback.
Ik ga ermee aan de slag.

Goed punt over de nummerstijl om die exclusief met getallen te doen.
